name: Run Python Linter and Formatter

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '*'

jobs:
    run_pylint:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set Up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Package Managers
          run: pipx install poetry

        - name: Install Dependencies
          run: poetry install

        - name: Run Linter and Formatter
          run: make lint
