name: Python Unit Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '*'

jobs:
    run_pyunit:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set Up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Package Managers
          run: |
            pipx install poetry
            pipx install conan
            sudo apt-get install ninja-build

        - name: Create Conan Default Profile
          run: conan profile detect

        - name: Run Tests
          run: make pyunit
